#!/usr/bin/env python3
"""Audit the code-only package for release-blocking files and text patterns."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path


TEXT_EXTENSIONS = {
    ".cff", ".csv", ".gitattributes", ".gitignore", ".html", ".js", ".json",
    ".md", ".ps1", ".py", ".toml", ".txt", ".yml", ".yaml",
}
PROHIBITED_EXTENSIONS = {
    ".7z", ".doc", ".docx", ".gz", ".npz", ".pdf", ".ppt", ".pptx",
    ".rar", ".tif", ".tiff", ".xls", ".xlsx", ".zip",
}
EXCLUDED_DIRECTORIES = {".git", ".venv", "__pycache__", ".pytest_cache"}
MAX_FILE_BYTES = 10 * 1024 * 1024


@dataclass
class Finding:
    check: str
    passed: bool
    path: str
    detail: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--profile", choices=["private", "public"], default="private")
    parser.add_argument("--report", type=Path)
    return parser.parse_args()


def files_under(root: Path) -> list[Path]:
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file() and not any(part in EXCLUDED_DIRECTORIES for part in path.relative_to(root).parts)
    )


def add(findings: list[Finding], check: str, passed: bool, path: Path, detail: str) -> None:
    findings.append(Finding(check, bool(passed), path.as_posix(), detail))


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    files = files_under(root)
    findings: list[Finding] = []
    forbidden_markers = [
        "Chat" + "GPT",
        "Co" + "dex",
        "AI-" + "generated",
        "Generated by " + "AI",
        "assistant " + "response",
        "Here is the " + "code",
    ]
    secret_pattern = re.compile(
        r"(?i)(?:api[_-]?key|access[_-]?token|client[_-]?secret|password)\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{12,}"
    )
    windows_path = re.compile(r"(?i)(?:[A-Z]:\\(?:Users|博士|Program Files)|\\Users\\[^\\]+)")
    home_path = re.compile(r"/(?:home|Users)/[^/\s]+/")

    for path in files:
        relative = path.relative_to(root)
        add(
            findings,
            "file_size",
            path.stat().st_size <= MAX_FILE_BYTES,
            relative,
            f"{path.stat().st_size} bytes",
        )
        add(
            findings,
            "prohibited_extension",
            path.suffix.lower() not in PROHIBITED_EXTENSIONS,
            relative,
            path.suffix.lower() or "no extension",
        )
        if relative.parts and relative.parts[0] == "data" and path.suffix.lower() not in {".md"}:
            add(findings, "data_directory_content", False, relative, "only documentation is allowed under data/")
        if path.suffix.lower() not in TEXT_EXTENSIONS and path.name not in {"LICENSE", "CITATION.cff"}:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            add(findings, "utf8_text", False, relative, "text candidate is not UTF-8")
            continue
        for marker in forbidden_markers:
            add(findings, f"marker:{marker}", marker.lower() not in text.lower(), relative, "not present" if marker.lower() not in text.lower() else "prohibited marker found")
        add(findings, "secret_pattern", secret_pattern.search(text) is None, relative, "no credential-like assignment")
        add(findings, "absolute_windows_path", windows_path.search(text) is None, relative, "no local Windows path")
        add(findings, "absolute_home_path", home_path.search(text) is None, relative, "no local home path")
        add(findings, "temporary_filename", not re.search(r"(?i)(final_final|new_latest)", path.name), relative, "stable filename")

    if args.profile == "public":
        license_text = (root / "LICENSE").read_text(encoding="utf-8") if (root / "LICENSE").is_file() else ""
        add(
            findings,
            "public_license_selected",
            "No permission is granted" not in license_text,
            Path("LICENSE"),
            "replace private-review notice with an author-approved public license",
        )

    failed = [finding for finding in findings if not finding.passed]
    report = {
        "schema_version": 1,
        "profile": args.profile,
        "files_scanned": len(files),
        "checks": len(findings),
        "failed": len(failed),
        "all_passed": not failed,
        "failures": [asdict(finding) for finding in failed],
    }
    print(json.dumps(report, indent=2, ensure_ascii=False))
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())

